spring:
  application:
    name: tenant-billing-api
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/tenant_billing}
    username: ${DB_USERNAME:tenant_billing}
    password: ${DB_PASSWORD:tenant_billing}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      probes:
        enabled: true
springdoc:
  swagger-ui:
    path: /swagger-ui.html
server:
  port: ${PORT:8080}
